// ============================================================================
// Polyboard CIX Parser & Machine Spec
// Post-processor parser for Biesse Rover A (BiesseWorks / bSolid)
// ============================================================================

export interface CixBoring {
  id?: string;
  side: number; // 0=top, 1=bottom, 2=left, 3=right, 4=front, 5=back
  x: number;
  y: number;
  z: number;
  diameter?: number;
  depth: number;
  through?: boolean;
}

export interface CixRoute {
  id?: string;
  tool?: string;
  depth?: number;
  diameter?: number;
  points: Array<{ x: number; y: number; z?: number }>;
}

export interface ParsedCixPart {
  filename: string;
  partName?: string;
  programName?: string;
  material?: string;
  length: number;    // LPX
  width: number;     // LPY
  thickness: number; // LPZ
  borings: CixBoring[];
  routings: CixRoute[];
  rawLinesCount: number;
}

/**
 * Helper to parse key-value attributes from CIX lines like:
 * BEGIN MAINDATA LPX=800 LPY=600 LPZ=18 ...
 * or PARAM,NAME=X,VALUE=100
 */
function extractAttributes(line: string): Record<string, string> {
  const result: Record<string, string> = {};
  // Check for PARAM,NAME=...,VALUE=... pattern first
  const paramMatches = line.matchAll(/PARAM\s*,\s*NAME\s*=\s*"?([A-Z0-9_]+)"?\s*,\s*VALUE\s*=\s*(?:"([^"]*)"|([^\s,]+))/gi);
  for (const m of paramMatches) {
    const key = m[1].toUpperCase();
    const val = m[2] !== undefined ? m[2] : m[3];
    result[key] = val;
  }

  // Also match general KEY="VALUE" or KEY=VALUE
  const regex = /([A-Z0-9_]+)\s*=\s*(?:"([^"]*)"|([^\s,]+))/gi;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(line)) !== null) {
    const key = match[1].toUpperCase();
    if (key === "PARAM" || key === "NAME" || key === "VALUE") continue;
    const val = match[2] !== undefined ? match[2] : match[3];
    if (result[key] === undefined) {
      result[key] = val;
    }
  }
  return result;
}

function processBoringMacro(params: Record<string, string>, currentCount: number): CixBoring {
  const side = parseInt(params["SIDE"] || "0", 10);
  const x = parseFloat(params["X"] || "0");
  const y = parseFloat(params["Y"] || "0");
  const z = parseFloat(params["Z"] || "0");
  const depth = parseFloat(params["DP"] || params["DEPTH"] || "12");
  const diameter = parseFloat(params["DIA"] || params["DIAM"] || "5");
  const through = params["THR"] === "1" || params["THR"] === "YES";

  return {
    id: params["ID"] || `hole-${currentCount + 1}`,
    side: isNaN(side) ? 0 : side,
    x: isNaN(x) ? 0 : x,
    y: isNaN(y) ? 0 : y,
    z: isNaN(z) ? 0 : z,
    diameter: isNaN(diameter) ? 5 : diameter,
    depth: isNaN(depth) ? 12 : depth,
    through,
  };
}

/**
 * Parses CIX file content generated by Polyboard for Biesse Rover A CNC machine
 */
export function parseCix(cixContent: string, filename: string = ""): ParsedCixPart {
  const lines = cixContent.split(/\r?\n/);
  
  let length = 0;
  let width = 0;
  let thickness = 18;
  let material = "";
  const programName = filename.replace(/\.cix$/i, "");
  let partName = "";

  const borings: CixBoring[] = [];
  const routings: CixRoute[] = [];

  let inMacro = false;
  let currentMacroName = "";
  let currentMacroParams: Record<string, string> = {};
  let currentRoute: CixRoute | null = null;

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i].trim();
    if (!rawLine) continue;

    // Check MAINDATA
    if (rawLine.includes("BEGIN MAINDATA")) {
      const attrs = extractAttributes(rawLine);
      if (attrs["LPX"]) length = parseFloat(attrs["LPX"]) || 0;
      if (attrs["LPY"]) width = parseFloat(attrs["LPY"]) || 0;
      if (attrs["LPZ"]) thickness = parseFloat(attrs["LPZ"]) || 18;
      if (attrs["MATERIAL"]) material = attrs["MATERIAL"];
      if (attrs["CUSTSTR"]) partName = attrs["CUSTSTR"];
      continue;
    }

    // Single-line or multi-line MACRO
    const macroStart = rawLine.match(/BEGIN\s+MACRO\s+NAME=([A-Z0-9_]+)/i);
    if (macroStart) {
      const macroName = macroStart[1].toUpperCase();
      const lineAttrs = extractAttributes(rawLine);

      // Check if it finishes on the same line (e.g. BEGIN MACRO ... END MACRO)
      if (rawLine.includes("END MACRO")) {
        if (macroName === "BG" || macroName === "BORING" || macroName === "B" || macroName === "BV") {
          borings.push(processBoringMacro(lineAttrs, borings.length));
        }
        continue;
      }

      // Multi-line macro start
      inMacro = true;
      currentMacroName = macroName;
      currentMacroParams = { ...lineAttrs };

      if (currentMacroName === "ROUT" || currentMacroName === "ROUTG") {
        currentRoute = {
          id: currentMacroParams["ID"] || `route-${routings.length + 1}`,
          tool: currentMacroParams["TNM"] || currentMacroParams["TOOL"],
          diameter: parseFloat(currentMacroParams["DIA"] || "0"),
          depth: parseFloat(currentMacroParams["DP"] || "0"),
          points: [],
        };
      }
      continue;
    }

    // Inside Macro
    if (inMacro) {
      if (rawLine.startsWith("END MACRO")) {
        // Finalize macro
        if (currentMacroName === "BG" || currentMacroName === "BORING" || currentMacroName === "B" || currentMacroName === "BV") {
          borings.push(processBoringMacro(currentMacroParams, borings.length));
        } else if (currentMacroName === "START_POINT" && currentRoute) {
          const x = parseFloat(currentMacroParams["X"] || "0");
          const y = parseFloat(currentMacroParams["Y"] || "0");
          const z = parseFloat(currentMacroParams["Z"] || "0");
          currentRoute.points.push({ x, y, z });
        } else if ((currentMacroName === "LINE_EP" || currentMacroName === "ARC_EPP") && currentRoute) {
          const x = parseFloat(currentMacroParams["XE"] || currentMacroParams["X"] || "0");
          const y = parseFloat(currentMacroParams["YE"] || currentMacroParams["Y"] || "0");
          const z = parseFloat(currentMacroParams["ZE"] || currentMacroParams["Z"] || "0");
          currentRoute.points.push({ x, y, z });
        } else if ((currentMacroName === "ROUT" || currentMacroName === "ROUTG") && currentRoute) {
          if (currentRoute.points.length > 0) {
            routings.push(currentRoute);
          }
          currentRoute = null;
        }

        inMacro = false;
        currentMacroName = "";
        currentMacroParams = {};
        continue;
      }

      // Collect params inside macro
      const lineAttrs = extractAttributes(rawLine);
      Object.assign(currentMacroParams, lineAttrs);
    }
  }

  // Fallback dimension guess from filename or boring extents if 0
  if (length === 0 && borings.length > 0) {
    const maxX = Math.max(...borings.map(b => b.x));
    if (maxX > 0) length = Math.ceil((maxX + 50) / 10) * 10;
  }
  if (width === 0 && borings.length > 0) {
    const maxY = Math.max(...borings.map(b => b.y));
    if (maxY > 0) width = Math.ceil((maxY + 50) / 10) * 10;
  }

  return {
    filename,
    partName: partName || filename.replace(/\.cix$/i, ""),
    programName,
    material,
    length,
    width,
    thickness,
    borings,
    routings,
    rawLinesCount: lines.length,
  };
}
